package com.mcwtrpdoors.kikoz.init;


import com.mcwtrpdoors.kikoz.MacawsTrapdoors;

import net.minecraft.core.registries.Registries;
import net.minecraft.network.chat.Component;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.ItemStack;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.RegistryObject;

public class TabInit {
	
	public static final DeferredRegister<CreativeModeTab> CREATIVE_TABS = DeferredRegister.create(Registries.CREATIVE_MODE_TAB, MacawsTrapdoors.MOD_ID);

	public static final RegistryObject<CreativeModeTab> TRAPDOORITEMGROUP = CREATIVE_TABS.register("mcwtrpdoors", () -> CreativeModeTab.builder()
			.title(Component.translatable("itemGroup." + MacawsTrapdoors.MOD_ID))
			.icon(() -> new ItemStack(BlockInit.OAK_RANCH_TRAPDOOR.get()))
			.displayItems((enabledFeatures, entries) -> {
				entries.accept(ItemInit.PRINT_CLASSIC.get());
				entries.accept(ItemInit.PRINT_COTTAGE.get());
				entries.accept(ItemInit.PRINT_PAPER.get());
				entries.accept(ItemInit.PRINT_BEACH.get());
				entries.accept(ItemInit.PRINT_TROPICAL.get());
				entries.accept(ItemInit.PRINT_FOUR_PANEL.get());
				entries.accept(ItemInit.PRINT_BARRED.get());
				entries.accept(ItemInit.PRINT_MYSTIC.get());
				entries.accept(ItemInit.PRINT_SWAMP.get());
				entries.accept(ItemInit.PRINT_BAMBOO.get());
				entries.accept(ItemInit.PRINT_BLOSSOM.get());
				entries.accept(BlockInit.OAK_BARN_TRAPDOOR.get());
				entries.accept(BlockInit.OAK_BARRED_TRAPDOOR.get());
				entries.accept(BlockInit.OAK_BEACH_TRAPDOOR.get());
				entries.accept(BlockInit.OAK_COTTAGE_TRAPDOOR.get());
				entries.accept(BlockInit.OAK_FOUR_PANEL_TRAPDOOR.get());
				entries.accept(BlockInit.OAK_GLASS_TRAPDOOR.get());
				entries.accept(BlockInit.OAK_MYSTIC_TRAPDOOR.get());
				entries.accept(BlockInit.OAK_PAPER_TRAPDOOR.get());
				entries.accept(BlockInit.OAK_TROPICAL_TRAPDOOR.get());
				entries.accept(BlockInit.OAK_SWAMP_TRAPDOOR.get());
				entries.accept(BlockInit.OAK_BAMBOO_TRAPDOOR.get());
				entries.accept(BlockInit.OAK_BLOSSOM_TRAPDOOR.get());
				entries.accept(BlockInit.SPRUCE_BARN_TRAPDOOR.get());
				entries.accept(BlockInit.SPRUCE_BARRED_TRAPDOOR.get());
				entries.accept(BlockInit.SPRUCE_BEACH_TRAPDOOR.get());
				entries.accept(BlockInit.SPRUCE_CLASSIC_TRAPDOOR.get());
				entries.accept(BlockInit.SPRUCE_FOUR_PANEL_TRAPDOOR.get());
				entries.accept(BlockInit.SPRUCE_GLASS_TRAPDOOR.get());
				entries.accept(BlockInit.SPRUCE_MYSTIC_TRAPDOOR.get());
				entries.accept(BlockInit.SPRUCE_PAPER_TRAPDOOR.get());
				entries.accept(BlockInit.SPRUCE_TROPICAL_TRAPDOOR.get());
				entries.accept(BlockInit.SPRUCE_SWAMP_TRAPDOOR.get());
				entries.accept(BlockInit.SPRUCE_BAMBOO_TRAPDOOR.get());
				entries.accept(BlockInit.SPRUCE_BLOSSOM_TRAPDOOR.get());
				entries.accept(BlockInit.BIRCH_BARN_TRAPDOOR.get());
				entries.accept(BlockInit.BIRCH_BARRED_TRAPDOOR.get());
				entries.accept(BlockInit.BIRCH_BEACH_TRAPDOOR.get());
				entries.accept(BlockInit.BIRCH_CLASSIC_TRAPDOOR.get());
				entries.accept(BlockInit.BIRCH_COTTAGE_TRAPDOOR.get());
				entries.accept(BlockInit.BIRCH_FOUR_PANEL_TRAPDOOR.get());
				entries.accept(BlockInit.BIRCH_GLASS_TRAPDOOR.get());
				entries.accept(BlockInit.BIRCH_MYSTIC_TRAPDOOR.get());
				entries.accept(BlockInit.BIRCH_TROPICAL_TRAPDOOR.get());
				entries.accept(BlockInit.BIRCH_SWAMP_TRAPDOOR.get());
				entries.accept(BlockInit.BIRCH_BAMBOO_TRAPDOOR.get());
				entries.accept(BlockInit.BIRCH_BLOSSOM_TRAPDOOR.get());
				entries.accept(BlockInit.JUNGLE_BARN_TRAPDOOR.get());
				entries.accept(BlockInit.JUNGLE_BARRED_TRAPDOOR.get());
				entries.accept(BlockInit.JUNGLE_CLASSIC_TRAPDOOR.get());
				entries.accept(BlockInit.JUNGLE_COTTAGE_TRAPDOOR.get());
				entries.accept(BlockInit.JUNGLE_FOUR_PANEL_TRAPDOOR.get());
				entries.accept(BlockInit.JUNGLE_GLASS_TRAPDOOR.get());
				entries.accept(BlockInit.JUNGLE_MYSTIC_TRAPDOOR.get());
				entries.accept(BlockInit.JUNGLE_PAPER_TRAPDOOR.get());
				entries.accept(BlockInit.JUNGLE_TROPICAL_TRAPDOOR.get());
				entries.accept(BlockInit.JUNGLE_SWAMP_TRAPDOOR.get());
				entries.accept(BlockInit.JUNGLE_BAMBOO_TRAPDOOR.get());
				entries.accept(BlockInit.JUNGLE_BLOSSOM_TRAPDOOR.get());
				entries.accept(BlockInit.ACACIA_BARN_TRAPDOOR.get());
				entries.accept(BlockInit.ACACIA_BARRED_TRAPDOOR.get());
				entries.accept(BlockInit.ACACIA_BEACH_TRAPDOOR.get());
				entries.accept(BlockInit.ACACIA_CLASSIC_TRAPDOOR.get());
				entries.accept(BlockInit.ACACIA_COTTAGE_TRAPDOOR.get());
				entries.accept(BlockInit.ACACIA_FOUR_PANEL_TRAPDOOR.get());
				entries.accept(BlockInit.ACACIA_GLASS_TRAPDOOR.get());
				entries.accept(BlockInit.ACACIA_MYSTIC_TRAPDOOR.get());
				entries.accept(BlockInit.ACACIA_PAPER_TRAPDOOR.get());
				entries.accept(BlockInit.ACACIA_SWAMP_TRAPDOOR.get());
				entries.accept(BlockInit.ACACIA_BAMBOO_TRAPDOOR.get());
				entries.accept(BlockInit.ACACIA_BLOSSOM_TRAPDOOR.get());
				entries.accept(BlockInit.DARK_OAK_BARN_TRAPDOOR.get());
				entries.accept(BlockInit.DARK_OAK_BARRED_TRAPDOOR.get());
				entries.accept(BlockInit.DARK_OAK_BEACH_TRAPDOOR.get());
				entries.accept(BlockInit.DARK_OAK_CLASSIC_TRAPDOOR.get());
				entries.accept(BlockInit.DARK_OAK_COTTAGE_TRAPDOOR.get());
				entries.accept(BlockInit.DARK_OAK_GLASS_TRAPDOOR.get());
				entries.accept(BlockInit.DARK_OAK_MYSTIC_TRAPDOOR.get());
				entries.accept(BlockInit.DARK_OAK_PAPER_TRAPDOOR.get());
				entries.accept(BlockInit.DARK_OAK_TROPICAL_TRAPDOOR.get());
				entries.accept(BlockInit.DARK_OAK_SWAMP_TRAPDOOR.get());
				entries.accept(BlockInit.DARK_OAK_BAMBOO_TRAPDOOR.get());
				entries.accept(BlockInit.DARK_OAK_BLOSSOM_TRAPDOOR.get());
				entries.accept(BlockInit.CRIMSON_BARN_TRAPDOOR.get());
				entries.accept(BlockInit.CRIMSON_BEACH_TRAPDOOR.get());
				entries.accept(BlockInit.CRIMSON_CLASSIC_TRAPDOOR.get());
				entries.accept(BlockInit.CRIMSON_COTTAGE_TRAPDOOR.get());
				entries.accept(BlockInit.CRIMSON_FOUR_PANEL_TRAPDOOR.get());
				entries.accept(BlockInit.CRIMSON_GLASS_TRAPDOOR.get());
				entries.accept(BlockInit.CRIMSON_MYSTIC_TRAPDOOR.get());
				entries.accept(BlockInit.CRIMSON_PAPER_TRAPDOOR.get());
				entries.accept(BlockInit.CRIMSON_TROPICAL_TRAPDOOR.get());
				entries.accept(BlockInit.CRIMSON_SWAMP_TRAPDOOR.get());
				entries.accept(BlockInit.CRIMSON_BAMBOO_TRAPDOOR.get());
				entries.accept(BlockInit.CRIMSON_BLOSSOM_TRAPDOOR.get());
				entries.accept(BlockInit.WARPED_BARN_TRAPDOOR.get());
				entries.accept(BlockInit.WARPED_BARRED_TRAPDOOR.get());
				entries.accept(BlockInit.WARPED_BEACH_TRAPDOOR.get());
				entries.accept(BlockInit.WARPED_CLASSIC_TRAPDOOR.get());
				entries.accept(BlockInit.WARPED_COTTAGE_TRAPDOOR.get());
				entries.accept(BlockInit.WARPED_FOUR_PANEL_TRAPDOOR.get());
				entries.accept(BlockInit.WARPED_GLASS_TRAPDOOR.get());
				entries.accept(BlockInit.WARPED_PAPER_TRAPDOOR.get());
				entries.accept(BlockInit.WARPED_TROPICAL_TRAPDOOR.get());
				entries.accept(BlockInit.WARPED_SWAMP_TRAPDOOR.get());
				entries.accept(BlockInit.WARPED_BAMBOO_TRAPDOOR.get());
				entries.accept(BlockInit.WARPED_BLOSSOM_TRAPDOOR.get());
				entries.accept(BlockInit.MANGROVE_BARN_TRAPDOOR.get());
				entries.accept(BlockInit.MANGROVE_BARRED_TRAPDOOR.get());
				entries.accept(BlockInit.MANGROVE_BEACH_TRAPDOOR.get());
				entries.accept(BlockInit.MANGROVE_CLASSIC_TRAPDOOR.get());
				entries.accept(BlockInit.MANGROVE_COTTAGE_TRAPDOOR.get());
				entries.accept(BlockInit.MANGROVE_FOUR_PANEL_TRAPDOOR.get());
				entries.accept(BlockInit.MANGROVE_GLASS_TRAPDOOR.get());
				entries.accept(BlockInit.MANGROVE_PAPER_TRAPDOOR.get());
				entries.accept(BlockInit.MANGROVE_TROPICAL_TRAPDOOR.get());
				entries.accept(BlockInit.MANGROVE_MYSTIC_TRAPDOOR.get());
				entries.accept(BlockInit.MANGROVE_BAMBOO_TRAPDOOR.get());
				entries.accept(BlockInit.MANGROVE_BLOSSOM_TRAPDOOR.get());
				entries.accept(BlockInit.OAK_BARK_TRAPDOOR.get());
				entries.accept(BlockInit.SPRUCE_BARK_TRAPDOOR.get());
				entries.accept(BlockInit.BIRCH_BARK_TRAPDOOR.get());
				entries.accept(BlockInit.JUNGLE_BARK_TRAPDOOR.get());
				entries.accept(BlockInit.ACACIA_BARK_TRAPDOOR.get());
				entries.accept(BlockInit.DARK_OAK_BARK_TRAPDOOR.get());
				entries.accept(BlockInit.CRIMSON_BARK_TRAPDOOR.get());
				entries.accept(BlockInit.WARPED_BARK_TRAPDOOR.get());
				entries.accept(BlockInit.MANGROVE_BARK_TRAPDOOR.get());
				entries.accept(BlockInit.CHERRY_BARK_TRAPDOOR.get());
				entries.accept(BlockInit.BAMBOO_BARN_TRAPDOOR.get());
				entries.accept(BlockInit.BAMBOO_BARRED_TRAPDOOR.get());
				entries.accept(BlockInit.BAMBOO_BEACH_TRAPDOOR.get());
				entries.accept(BlockInit.BAMBOO_CLASSIC_TRAPDOOR.get());
				entries.accept(BlockInit.BAMBOO_COTTAGE_TRAPDOOR.get());
				entries.accept(BlockInit.BAMBOO_FOUR_PANEL_TRAPDOOR.get());
				entries.accept(BlockInit.BAMBOO_GLASS_TRAPDOOR.get());
				entries.accept(BlockInit.BAMBOO_MYSTIC_TRAPDOOR.get());
				entries.accept(BlockInit.BAMBOO_PAPER_TRAPDOOR.get());
				entries.accept(BlockInit.BAMBOO_TROPICAL_TRAPDOOR.get());
				entries.accept(BlockInit.BAMBOO_SWAMP_TRAPDOOR.get());
				entries.accept(BlockInit.BAMBOO_BLOSSOM_TRAPDOOR.get());
				entries.accept(BlockInit.CHERRY_BARN_TRAPDOOR.get());
				entries.accept(BlockInit.CHERRY_BARRED_TRAPDOOR.get());
				entries.accept(BlockInit.CHERRY_BEACH_TRAPDOOR.get());
				entries.accept(BlockInit.CHERRY_CLASSIC_TRAPDOOR.get());
				entries.accept(BlockInit.CHERRY_COTTAGE_TRAPDOOR.get());
				entries.accept(BlockInit.CHERRY_FOUR_PANEL_TRAPDOOR.get());
				entries.accept(BlockInit.CHERRY_GLASS_TRAPDOOR.get());
				entries.accept(BlockInit.CHERRY_PAPER_TRAPDOOR.get());
				entries.accept(BlockInit.CHERRY_TROPICAL_TRAPDOOR.get());
				entries.accept(BlockInit.CHERRY_MYSTIC_TRAPDOOR.get());
				entries.accept(BlockInit.CHERRY_BAMBOO_TRAPDOOR.get());
				entries.accept(BlockInit.CHERRY_SWAMP_TRAPDOOR.get());
				entries.accept(BlockInit.OAK_RANCH_TRAPDOOR.get());
				entries.accept(BlockInit.SPRUCE_RANCH_TRAPDOOR.get());
				entries.accept(BlockInit.BIRCH_RANCH_TRAPDOOR.get());
				entries.accept(BlockInit.JUNGLE_RANCH_TRAPDOOR.get());
				entries.accept(BlockInit.ACACIA_RANCH_TRAPDOOR.get());
				entries.accept(BlockInit.DARK_OAK_RANCH_TRAPDOOR.get());
				entries.accept(BlockInit.CRIMSON_RANCH_TRAPDOOR.get());
				entries.accept(BlockInit.WARPED_RANCH_TRAPDOOR.get());
				entries.accept(BlockInit.MANGROVE_RANCH_TRAPDOOR.get());
				entries.accept(BlockInit.CHERRY_RANCH_TRAPDOOR.get());
				entries.accept(BlockInit.BAMBOO_TRAPDOOR.get());
				entries.accept(BlockInit.METAL_TRAPDOOR.get());
				entries.accept(BlockInit.METAL_WARNING_TRAPDOOR.get());
				entries.accept(BlockInit.METAL_FULL_TRAPDOOR.get());
				entries.accept(BlockInit.OAK_BARREL_TRAPDOOR.get());
				entries.accept(BlockInit.SPRUCE_BARREL_TRAPDOOR.get());
				entries.accept(BlockInit.BIRCH_BARREL_TRAPDOOR.get());
				entries.accept(BlockInit.JUNGLE_BARREL_TRAPDOOR.get());
				entries.accept(BlockInit.ACACIA_BARREL_TRAPDOOR.get());
				entries.accept(BlockInit.DARK_OAK_BARREL_TRAPDOOR.get());
				entries.accept(BlockInit.CRIMSON_BARREL_TRAPDOOR.get());
				entries.accept(BlockInit.WARPED_BARREL_TRAPDOOR.get());
				entries.accept(BlockInit.MANGROVE_BARREL_TRAPDOOR.get());
				entries.accept(BlockInit.CHERRY_BARREL_TRAPDOOR.get());
				entries.accept(BlockInit.BAMBOO_BARREL_TRAPDOOR.get());
			})
			.build());
}

